<!DOCTYPE html>
<html dir="ltr">
<head>
    <title>{{$subject}}</title>
</head>
<body style="text-align: left">
   
Dear Team
<br><br>
I have excellent technical and communication skills, looking for an opportunity to prove myself and gain experience from others in the company.
<br><br>
Please Find below link to review my CV from easyjob.com.sa
<br><br>
<a href="{{ asset($CV) }}" target="_blank">View CV</a>
<br><br>
Thank you,
<br><br><br>
Name : [ {{ $name }} ] <br>
Email: [ {{ $email }} ] <br>
Mobile : [ {{ $phone }} ] <br>
@if(isset($linkedin) && !empty($linkedin))
Linkedin : [ {{ $linkedin }} ] <br>
@endif
<br><br><br>
This Email was generated by <a href="https://easyjob.com.sa" target="_blank">easyjob</a>
</body>
</html>


